language: php

php:
  - 5.5
  - 5.6
  - 7.0

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer create-project

before_script:
  - mysql -e 'CREATE DATABASE yii2mod_base_test;';
  - cd tests/bin && php yii migrate --interactive=0 && php yii rbac/migrate --interactive=0 && cd ../..
  - php -S localhost:8080 -t web > /dev/null 2>&1 &

script:
  - vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff
  - composer exec codecept run
